name: C/C++ CI

on:
  push:
    branches: [ "tf2classic-cmake" ]
  pull_request:
    branches: [ "tf2classic-cmake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: mkdir ./build & cd ./build & cmake ..
    - name: make
      run: make
